// Generated by CoffeeScript 1.9.1
(function() {
  var express, passport, router;

  express = require('express');

  passport = require('passport');

  router = express.Router();

  router.get('/', passport.authenticate('github'), function(req, res) {
    return console.log('something went wrong in the github auth');
  });

  router.get('/callback', passport.authenticate('github', {
    failureRedirect: '/failed'
  }), function(req, res) {
    console.log('github authenticated');
    return res.redirect('/');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=github-auth.js.map
