// Generated by CoffeeScript 1.9.1
(function() {
  var express, router;

  express = require('express');

  router = express.Router();

  router.get('/', function(req, res, next) {
    return res.send('respond with a resource');
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=users.js.map
