// Generated by CoffeeScript 1.9.1
(function() {
  var User, UserStore;

  User = require('../models/user');

  UserStore = (function() {
    function UserStore() {}

    UserStore.prototype.find = function(email) {
      if (email === 'info@grokbit.com') {
        return this.createInstance();
      } else {
        return null;
      }
    };

    UserStore.prototype.findByKey = function(key) {
      if (key === 'info@grokbit.com') {
        return this.createInstance();
      } else {
        return null;
      }
    };

    UserStore.prototype.createInstance = function() {
      var validUser;
      validUser = new User();
      validUser.email = 'info@grokbit.com';
      validUser.providerKey = validUser.email;
      validUser.password = 'mypassword';
      validUser.name = 'Grokbit';
      return validUser;
    };

    return UserStore;

  })();

  module.exports = UserStore;

}).call(this);

//# sourceMappingURL=userStore.js.map
