// Generated by CoffeeScript 1.9.1
(function() {
  var User;

  User = (function() {
    function User() {}

    User.prototype.email = '';

    User.prototype.password = '';

    User.prototype.providerType = '';

    User.prototype.providerKey = '';

    User.prototype.name = '';

    return User;

  })();

  module.exports = User;

}).call(this);

//# sourceMappingURL=user.js.map
