// Generated by CoffeeScript 1.9.1
(function() {
  var bodyParser, cookieParser, express, favicon, logger, path, routes, users;

  express = require('express');

  path = require('path');

  favicon = require('serve-favicon');

  logger = require('morgan');

  cookieParser = require('cookie-parser');

  bodyParser = require('body-parser');

  routes = require('./routes/index');

  users = require('./routes/users');

}).call(this);

//# sourceMappingURL=app.js.map
